#!/bin/bash

function ubuntu() {
  sudo apt -y update
  sudo apt -y upgrade

  sudo apt -y install git ripgrep python3-pip python3-venv jq
}

function rhel() {
  dnf -y update

  dnf -y install epel-release
  dnf config-manager --set-enabled crb

  dnf -y install git git-lfs ripgrep python3-pip python3-virtualenv jq
  dnf -y clean all
}

OS_ID_LIKE=$(. /etc/os-release && echo "$ID_LIKE")
OS_ID=$(. /etc/os-release && echo "$ID")
if [[ "$OS_ID_LIKE" =~ rhel ]]; then
  rhel
elif [[ "$OS_ID" =~ ubuntu ]]; then
  ubuntu
else
  echo "Got ID_LIB $OS_ID_LIKE and ID $OS_ID, but that isn't implemented"
  exit 1
fi
