#!/bin/bash

function ubuntu() {
  apt -y install git
}

function rhel() {
  dnf -y install git
}

OS_ID_LIKE=$(. /etc/os-release && echo "$ID_LIKE")
OS_ID=$(. /etc/os-release && echo "$ID")
if [[ "$OS_ID_LIKE" =~ rhel ]]; then
  rhel
elif [[ "$OS_ID" =~ ubuntu ]]; then
  ubuntu
else
  echo "Got ID_LIB $OS_ID_LIKE and ID $OS_ID, but that isn't implemented"
  exit 1
fi

if [ -d "$HOME/.liquidprompt" ]; then
  rm -rf "$HOME/.liquidprompt"
fi

mkdir -p "$HOME/.liquidprompt"
git clone --branch=stable https://github.com/liquidprompt/liquidprompt.git "$HOME/.liquidprompt/liquidprompt"

# Config should be laid down by dotfiles

exit 0
