#!/bin/bash

install_dir="/opt/liquidprompt"
if [[ -n "${LIQUIDPROMPT_INSTALL_DIR}" ]]; then
  install_dir="${LIQUIDPROMPT_INSTALL_DIR}"
fi

echo "Installing Liquidprompt to ${LIQUIDPROMPT_INSTALL_DIR}"

function ubuntu() {
  apt -y update
  apt -y install git
}

function rhel() {
  dnf -y install git
}

OS_ID_LIKE=$(. /etc/os-release && echo "$ID_LIKE")
OS_ID=$(. /etc/os-release && echo "$ID")
if [[ "$OS_ID_LIKE" =~ rhel ]]; then
  rhel
elif [[ "$OS_ID" =~ ubuntu ]]; then
  ubuntu
else
  echo "Got ID_LIB $OS_ID_LIKE and ID $OS_ID, but that isn't implemented"
  exit 1
fi

mkdir -p "${LIQUIDPROMPT_INSTALL_DIR}"
git clone --branch=stable https://github.com/liquidprompt/liquidprompt.git "${LIQUIDPROMPT_INSTALL_DIR}"

# Config should be laid down by dotfiles

exit 0
