#!/bin/bash

version="stable"
install_dir="/opt/"
install_user="$(whoami)"

if [[ -n "${NVIM_INSTALL_DIR}" ]]; then
  install_dir="${NVIM_INSTALL_DIR}"
  mkdir -p "${install_dir}"
fi

if [[ -n "${NVIM_INSTALL_VERSION}" ]]; then
  version="${NVIM_INSTALL_VERSION}"
fi

if [[ -n "${NVIM_INSTALL_USER}" ]]; then
  echo "${NVIM_INSTALL_USER} set as install user"
  install_user="${NVIM_INSTALL_USER}"
fi

if [[ "$install_user" =~ ^root$ ]]; then
  config_dir="/root/.config"
else
  config_dir=$(realpath ~${install_user})
  config_dir="${config_dir}/.config"
fi
echo "Installing Neovim '${version}' to ${install_dir}"

pushd() {
  command pushd "$@" >/dev/null
}

popd() {
  command popd "$@" >/dev/null
}

function ubuntu() {
  # installs
  sudo apt update
  sudo apt -y install make curl cmake gettext fd-find wget ninja-build cmake build-essential libreadline-dev unzip npm python3-pip python3-venv git
}

function rhel() {
  sudo dnf -y update
  sudo dnf -y install yum-utils
  sudo dnf config-manager --set-enabled crb
  sudo dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
  sudo dnf -y install cmake make git wget ninja-build gcc gettext glibc-gconv-extra unzip npm readline-devel ncurses-devel libevent-devel readline-devel

  # fd
  sudo dnf -y copr enable tkbcopr/fd
  sudo dnf -y install fd
  sudo dnf clean all
}

OS_ID_LIKE=$(. /etc/os-release && echo "$ID_LIKE")
OS_ID=$(. /etc/os-release && echo "$ID")
if [[ "$OS_ID_LIKE" =~ rhel ]]; then
  rhel
elif [[ "$OS_ID" =~ ubuntu ]]; then
  ubuntu
else
  echo "Got ID_LIB $OS_ID_LIKE and ID $OS_ID, but that isn't implemented"
  exit 1
fi

pushd "$install_dir"
# Neovim
git clone https://github.com/neovim/neovim
pushd "$install_dir/neovim"
git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo
chown -R $install_user: "$install_dir/neovim"
make install
popd

# Lua
wget -qO- https://www.lua.org/ftp/lua-5.1.tar.gz | tar zx
pushd lua-5.1
make linux && make install
popd
chown -R $install_user: lua-5.1

# Luarocks
wget -qO- https://luarocks.org/releases/luarocks-3.11.1.tar.gz | tar zx
pushd "luarocks-3.11.1"
./configure && make && make install
popd
chown -R $install_user: "$install_dir/luarocks-3.11.1"
popd
popd

exit 0
